project_name: genieacs-mcp
release:
  github:
    owner: GeiserX
    name: genieacs-mcp
  draft: false
  prerelease: auto # tag “v0.3.0-rc1” becomes pre-release

builds:
  - id: bin
    main: ./cmd/server
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/geiserx/genieacs-mcp/version.Version={{ .Version }}
      - -X github.com/geiserx/genieacs-mcp/version.Commit={{ .ShortCommit }}
      - -X github.com/geiserx/genieacs-mcp/version.Date={{ .Date }}

archives:
  - id: dist
    builds: [bin]
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

dockers:
  # ------------- amd64 -------------
  - image_templates:
      - "drumsergio/genieacs-mcp:{{ .Tag }}-amd64"
      - "drumsergio/genieacs-mcp:latest-amd64"
    dockerfile: Dockerfile
    goos:   linux
    goarch: amd64
    use:    buildx
    files:
      - . 
    build_flag_templates:
      - "--platform=linux/amd64"
  # ------------- arm64 -------------
  - image_templates:
      - "drumsergio/genieacs-mcp:{{ .Tag }}-arm64"
      - "drumsergio/genieacs-mcp:latest-arm64"
    dockerfile: Dockerfile
    goos:   linux
    goarch: arm64
    use:    buildx
    files:
      - . 
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  # stitch the per-arch images into a combined tag = multi-arch
  - name_template: 'drumsergio/genieacs-mcp:{{ .Tag }}'
    image_templates:
      - 'drumsergio/genieacs-mcp:{{ .Tag }}-amd64'
      - 'drumsergio/genieacs-mcp:{{ .Tag }}-arm64'
  - name_template: 'drumsergio/genieacs-mcp:latest'
    image_templates:
      - 'drumsergio/genieacs-mcp:latest-amd64'
      - 'drumsergio/genieacs-mcp:latest-arm64'

snapshot:
  name_template: "snapshot-{{ .ShortCommit }}"

changelog:
  groups:
    - title: "🚀 Features"
      regexp: '^feat'
    - title: "🐛 Fixes"
      regexp: '^fix'